### ISSUE TITLE
Question regarding bird.conf

### ISSUE THREAD

**Issue by Peter-LiDP** [SpaceNetLab/StarryNet#3]
I tried to deploy StarryNet on my device, and I found that each node can only communicate with four of its neighbors in the emulation. Then I realized there was no bird.conf provided in the folder. Do I need to manually set up bird.conf to support OSPF? Or can I get the bird.conf from somewhere else?

**Comment by dremofly** [comment]
I had the same question. And I am trying to manually create one.

**Comment by yangtaodeng** [comment]
Actually, you do not need to prepare a bird.conf on your own now. The "bird.conf"s will be generated automatically in your folder. You will find a folder named "conf" during emulation. I just tried without any change to this repository, and the routing works. Try the following methods to check it:
1. check whether there is a folder named "conf" during emulation.
2. ps -ef to check whether will are bird processes for routing during emulation.
3. if bird is running on each container, use commands like "route" to see the routing table of the containers.
4. if the routing table merely has four subnets, wait a little while, the routing needs time for initializing.

**Comment by dremofly** [comment]
Thanks for your kindness. 

I have successfully solved the routing problem without creating a `bird.conf`. Following the original code of function `sn_copy_conf` in `sn_orchestrater.py`, I still encounter the problem that some containers failed to start `bird` daemon. The code starting `bird` daemon of every container is 
```python
os.system("docker exec -it " + str(container_idx) + " bird -c B" +
              str(current + 1) + ".conf")
```
To see the output of this `docker exec ...` command, I change the above code into 
```python
result = subprocess.run(["docker", "exec", str(container_idx), "bird", "-c", "B"+str(current+1)+".conf"], capture_output=True, text=True)
print("[exec result] ", result.stdout)

result2 = subprocess.run(["docker", "exec", str(container_idx), "birdc", "show", "protocol"], capture_output=True, text=True)
print("[exec result2] ", result2.stdout)
```
It turns out that every container start `bird` daemon successfully.
